### PR TITLE
Fix  #81

### LINKED ISSUE #81: Vulnerable to Broken Access Control
Dhabaleshwar Das discovered and reported this Broken Access Control vulnerability in WordPress Arconix Shortcodes Plugin to Patchstack.

**Steps to reproduce**

The plugin lacks proper nonce implementation for an action, exposing users to Cross-Site Request Forgery (CSRF) attack. This vulnerability could allow an attacker to perform malicious actions on behalf of the authenticated user without their consent.

1- First install and configure the plugin.

2- After activation, on the left side in "Plugins" tab, now on top of page allow arconix shortcodes to collect data. After that you'll see an option under "Arconix Shortcodes", that is "Reset Usage Tracking", click on it and then intercept the request, you'll see that no nonce is implemented for this action.

3- This improper validation of nonce causes CSRF attacks, wherein an attacker can forge a request to perform unauthorized actions on behalf of the user who is currently authenticated.

The crafted HTML request can be seen here:

https://patchstack.com/database/report-preview/fac03b5b-0005-477c-bfd1-05d587fea0b4
PIN code to access the report information is here: j82t1X4RjLLjanyB

<html>

<body>
<script>history.pushState('', '', '/')</script>
<form action="http://localhost/wordpress/wp-admin/plugins.php">
<input type="hidden" name="ts&#95;action" value="reset&#95;tracking" />
<input type="submit" value="Submit request" />
</form>
</body>
</html>

**Expected behavior**

Additional comment by Patchstack

Unauth BAC on ts_reset_tracking_setting function. Apply proper permission and nonce check

**Additional field**

Ticket: https://support.tychesoftwares.com/conversation/2678?folder_id=13

### PR DESCRIPTION
**Pull request by nidhi-tatosaniya**
Fixed vulnerable to Broken Access Control added nonce check  Fix https://github.com/TycheSoftwares/arconix-shortcodes/issues/81

### CODE REVIEW

File: includes/component/tracking-data/ts-tracking.php [hunk 1]
```diff
@@ -168,12 +169,16 @@ public static function ts_add_new_settings_field ( $ts_settings ) {
...
 	 */
 	public static function ts_reset_tracking_setting () {
-
-		if ( isset ( $_GET [ 'ts_action' ] ) && 'reset_tracking' == $_GET [ 'ts_action' ] ) {
-			delete_option( self::$plugin_prefix . '_allow_tracking' );
-			delete_option( self::$plugin_prefix . '_ts_tracker_last_send' );
-			$ts_url = remove_query_arg( 'ts_action' );
-			wp_safe_redirect( $ts_url );
+		$nonce = isset( $_GET ['nonce'] ) ? $_GET['nonce'] : '';//phpcs:ignore
+		if ( is_user_logged_in() && current_user_can( 'manage_options' ) && wp_verify_nonce( $nonce, 'ts_nonce_action' ) ) {
```
Comment (handelce) [inline includes/component/tracking-data/ts-tracking.php:173]: @nidhi-tatosaniya Let's combine the two "if" conditions into one.

**Review by handelce — CHANGES_REQUESTED** [review]

**Review by handelce — APPROVED** [review]
